[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "capstone"
version = "0.1.0"
description = "Capstone utilities"
authors = [{ name = "Your Name" }]
dependencies = []